### ISSUE TITLE
Invalid redirect uri when Logout from OpenID Provider with Keycloak

### ISSUE THREAD

**Issue by hoanpvzz** [jenkinsci/oic-auth-plugin#153]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Keycloak 19.0.0-legacy
  Jenkins 2.361.2
  OpenId Connect Authentication Plugin Version 2.1
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins deploy with Ubuntu 20.04 LTS (no agents)

### Reproduction steps

1. Logout from OpenID Provider

### Expected Results

- User logout both jenkins and Key Cloak, then return to Login Page Keycloak

### Actual Results

Error Invalid Redirect Uri

### Anything else?

I want to use Logout from OpenID Provider,  but when I config Post Logout redirect URL  I see that URL not be encoded when click Jenkins Logout button.

Link logout when use Keycloak:
**_https://sso.xxx.com/auth/realms/xxx/protocol/openid-connect/logout?post_logout_redirect_uri=https%3A%2F%2Fsso.xxx.com%2Fauth%2Frealms%2Fxxx%2Faccount%2Ftotp&id_token_hint=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA...._**

Link logout when use Jenkins:
**_https://sso.xxx.com/auth/realms/xxx/protocol/openid-connect/logout?id_token_hint=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA.....&state=ZWU0ZWNlY2UtYmM0MS00&post_logout_redirect_uri=https://jenkins.xxx.com/_**

**Comment by michael-doubez** [comment]
Hello,

I notice that the `post_logout_redirect_uri` is not URL Encoded.
Is it due to a different copy/paste ?

If not, that's the bug but then I don't understand how the feature ever worked.

**Comment by michael-doubez** [comment]
Note: Related to #95 ?

**Comment by michael-doubez** [comment]
From the code, I guest it is a bug.
https://github.com/jenkinsci/oic-auth-plugin/blob/0e6ab26eab8a34e8ea3ed86363d83ddd0927ef5f/src/main/java/org/jenkinsci/plugins/oic/OicSecurityRealm.java#L644

This should be URL encoded.

I hope it will be fixed in next release (this week).

**Comment by michael-doubez** [comment]
Fixed

**Comment by michael-doubez** [comment]
Oups

**Comment by michael-doubez** [comment]
MAy also fix https://issues.jenkins.io/browse/JENKINS-66459

**Comment by klaask** [comment]
> I hope it will be fixed in next release (this week).

Thank you, I'm now able to logout in jenkins and keycloak 19.0.3. But I had to switch from automatic configuration to manual configuration and enter a Post logout redirect URL. Otherwise keycloak throws an invalid_redirect_uri error because of an empty url parameter post_logout_redirect_uri:

`/realms/xxxxx/protocol/openid-connect/logout?id_token_hint=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJLeVkyejhtQ2h6dG9tb3lDUHphNWw1bG9hdVNublM3RFVNYWdkT1ZsUnBVIn0.eyJl…cawFCQ9iWQGHg&state=YTBkM…C00&post_logout_redirect_uri=
`

I'm not sure but maybe getPostLogOutUrl2 should also check on an empty string like doCheckPostLogoutRedirectUrl does:

`if (this.postLogoutRedirectUrl != null) && !postLogoutRedirectUrl.equals("") {`

**Comment by hoanpvzz** [comment]
Hi @klaask , can u share config logout_uri. I still not success logout with Invalid redirect uri after upgrade plugin :(

**Comment by michael-doubez** [comment]
I'll fix that in #113.

Thanks for the feedback.

**Comment by michael-doubez** [comment]
@hoanpvzz can you please share the URL generated ?

**Comment by hoanpvzz** [comment]
> @hoanpvzz can you please share the URL generated ?

https://sso.xxx.com/auth/realms/xxx/protocol/openid-connect/logout?id_token_hint=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIzWWhQcGV6eE1Ycll1YUpfZ3dybkhXQk8wNGlMUEs2YzNUV090aGo4RVRFIn0.eyJleHAiOjE2NjY5Njk1NTgsIm........&post_logout_redirect_uri=https%3A%2F%2Fjenkins.xxx.com%2F

This is generate URL logout use plugin v2.2 with post_logout_url  **_https://jenkins.xxx.com/_** but it not work.
Maybe I miss something on Keycloak ?

**Comment by hoanpvzz** [comment]
> @hoanpvzz can you please share the URL generated ?

After  upgrade to keycloak 19.0.3 i config Option **_Valid post logout redirect URIs_** same as value in jenkins  and it work :)
I don't know how it work with older version keycloak ??
